# Generated by Django 6.0.3 on 2026-04-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('campaign', 'influencer')},
        ),
    ]
